name: Create Issues on Multiple Repositories

on:
  push:
    branches:
      - main

jobs:
  create_issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Issues
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const repos = ['NuGet/NuGetGallery', 'NuGet/NuGet.Jobs', 'lyndaidaii/TestWithSVG']; // List of repositories
              const title = 'New Issue Title';
              const body = 'Description of the issue...';

              async function createIssue(repo) {
                const [owner, repoName] = repo.split('/');
                const issue = await github.issues.create({
                  owner: owner,
                  repo: repoName,
                  title: title,
                  body: body
                });
                console.log(`Issue created in ${repo}:`, issue.data.html_url);
              }

              for (const repo of repos) {
                await createIssue(repo);
              }
            } catch (error) {
              console.error('Error:', error.message);
              core.setFailed(error.message);
            }