name: Create Issues on Multiple Repositories

on:
  workflow_dispatch:  # Manually triggered workflow

jobs:
  create_issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Issues
        uses: actions/github-script@v5
        with:
          github-token: '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'
          script: |
            try {
              //const repos = [ 'NuGet/NuGetGallery', 'NuGet/NuGet.Jobs','lyndaidaii/NuGetReadMeTemplate', 'lyndaidaii/TestWithSVG']; // List of repositories
              const packages = {
                'Testpackages3': 'lyndaidaii/NuGetReadMeTemplate',
                'TestPackages4': 'lyndaidaii/TestWithSVG',
                'TestPackages6': 'lyndaidaii/TestWithSVG'
              };

              const skipRepos=[
                'DotNetAnalyzers/StyleCopAnalyzers',
                'bchavez/Bogus',
                'shimat/opencvsharp',
                'MahApps/MahApps.Metro',
                'dotnet/BenchmarkDotNet',
                'killnine/s7netplus',
                'IdentityModel/IdentityModel',
                'MapsterMapper/Mapster',
                'AutoFixture/AutoFixture',
                'PrismLibrary/Prism',
                'huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore',
                'coverlet-coverage/coverlet',
                'ThreeMammals/Ocelot',
                'xceedsoftware/wpftoolkit',
                'cefsharp/cefsharp',
                'RicoSuter/NSwag',
                'stripe/stripe-dotnet',
                'hardkoded/puppeteer-sharp',
                'twilio/twilio-csharp',
                'MaterialDesignInXAML/MaterialDesign',
                'TobiasBuchholz/Plugin.Firebase',
                'Fody/Fody',
                'Firebase/firebase-admin-dotnet',
                'zaafar/ClickableTransparentOverlay',
                'discord-net/Discord.Net',
                'mini-software/MiniExcel',
                'googleapis/google-api-dotnet-client',
                'chrishaly/bc-csharp',
                'Xabaril/AspNetCore.Diagnostics.HealthChecks',
                'aws/aws-sdk-net/',
                'SixLabors/ImageSharp.Drawing',
                'ststeiger/PdfSharpCore',
                'protobuf-net/protobuf-net',
                'aaubry/YamlDotNet/wiki',
                'jwt-dotnet/jwt',
                'Ruslan-B/FFmpeg.AutoGen',
                'spectreconsole/spectre.console',
                'mellinoe/imgui.net',
                'dotnet/MQTTnet',
                'appium/dotnet-client',
                'adamhathcock/sharpcompress',
                'mganss/HtmlSanitizer',
                'googleapis/google-api-dotnet-client',
                'google/google-api-dotnet-client',
                'neuecc/MessagePack-CSharp',
                'Exiled-Team/EXILED',
                'helix-toolkit/helix-toolkit',
                'khellang/Scrutor',
                'sergey-shandar/getboost',
                'Blazored/SessionStorage',
                'serilog-contrib/serilog-sinks-elasticsearch',
                'redth/ZXing.Net.Maui',
                'mattfrear/Swashbuckle.AspNetCore.Filters',
                'altmann/FluentResults',
                'step-up-labs/firebase-database-dotnet'
              ]

              const createdIssues = {}; // Object to track created issues by repository
              
              const markdownContent = `
              We've noticed that your package on NuGet.org is missing a README file.

              ## Why READMEs are Important
              Our customer research indicates that one of the top problems that package consumers face is insufficient package documentation such as README files. Adding a README file to your package will help users quickly understand what the package is and what it does. Since your README will be the first impression for users when they view your package on NuGet.org, it is crucial for authors to write and include high-quality READMEs for their packages.

              ## Get Started with READMEs

              ### How to Add a README
              If you're new to NuGet READMEs, follow guidance on [how to add one to your package](https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/).

              ### How to write high quality of READMEs
              Follow [a blog post](https://devblogs.microsoft.com/nuget/write-a-high-quality-readme-for-nuget-packages/) with README best practices and a template file to help you get started. 

              ## We Value Your Feedback
              We value your feedback. If you encounter any issues or have suggestions, please reply to this issue.

              Thank you for your contribution to the NuGet community.
              `;
              
              async function createIssue(repo, packageName) {
                const [owner, repoName] = repo.split('/');
                const response = await github.rest.issues.create({
                  owner: owner,
                  repo: repoName,
                  title: `${packageName} is missing NuGet package README file`,
                  body: markdownContent
                });
                console.log(`Issue created in ${repo}: for package ${packageName} `, response.data.html_url);
                createdIssues[repo] = true;
              }
              for (const packageName in packages) {
                if (Object.hasOwnProperty.call(packages, packageName)) {
                  const repo = packages[packageName];
                  if (!createdIssues[repo] && !skipRepos.includes(repo))
                  try {
                    //await new Promise(resolve => setTimeout(resolve, 60000));
                    await createIssue(repo, packageName);
                  } catch (error) {
                    console.error(`Error occurred while processing package ${packageName}: ${error.message}`);
                    core.setFailed(error.message);
                  }
                }
              }
            } catch (error) {
              console.error('Error:', error.message);
              core.setFailed(error.message);
            }
