on:
  push:
    branches:
      - main

jobs:
  your_job_name:
    runs-on: ubuntu-latest

    steps:
      - name: Cache
        uses: actions/cache@v4.0.0
        # Define your actions or commands here

      - name: Create Github Issue
        uses: dacbd/create-issue-action@v1.2.1
        with:
          token: ${{ github.token }}
          title: Simple test issue
          body: my new issue
            
